services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: youtube_downloader
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
