FROM php:8.4-fpm-alpine
COPY --from=composer:2.8 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV COMPOSER_HOME="/opt/composer"
ENV PATH="$PATH:/opt/composer/vendor/bin"
RUN apk update &&\
    apk add zip npm python3 yt-dlp ffmpeg supervisor &&\
    docker-php-ext-install pdo_mysql

COPY ./app /var/www/html/youtube_downloader
COPY ./laravel-worker.conf /etc/supervisor/conf.d/
WORKDIR /var/www/html/youtube_downloader