services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: youtube_downloader
    volumes:
      - ./app:/var/www/html/youtube_downloader
      - ~/reverse-proxy/var/www/html/youtube_downloader/public:/var/www/html/youtube_downloader/public
    ports:
      - "9000:9000"
    tty: true
    networks:
      - proxy_network
      - default
    command: php artisan queue:work

  db:
    image: mysql:8.3
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  proxy_network:
    external: true