services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: youtube_downloader
    volumes:
      - ./app:/var/www/html
      - ~/reverse-proxy/staticfiles/youtube_downloader:/var/www/html
    ports:
      - "9000:9000"
    tty: true
    networks:
      - proxy_network
      - default

  db:
    image: mysql:8.3
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  proxy_network:
    external: true